theme = "purehugo"
baseURL = "http://tpristavec.github.io/test"
languageCode = "en-us"
title = "Teja Pristavec"
publishDir = "docs"
disqusShortname = ""

[params]
  description = "Postdoctoral Research Associate @ UVA BII SDAD"
  twitterName = "tpristavec"
  githubName = "tpristavec"
  linkedinName = "tejapristavec"
  google_analytics = ""
  
[menu]
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "CV"
    weight = 3
    url = "/cv/"
[[menu.main]]
    name = "Posts"
    weight = 4
    identifier = "post"
    url = "/post/"
[[menu.main]]
    name = "Contact"
    weight = 5
    url = "/contact/"
    
[social]
  linkedin = "tejapristavec"
  twitter = "tpristavec"
  github = "tpristavec"
