theme = "purehugo"
baseURL = "http://tpristavec.github.io/test"
languageCode = "en-us"
title = "Teja Pristavec"
publishDir = "docs"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "CV"
    url = "/cv/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/tpristavec"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/tpristavec"
