---
title: "Teaching"
author: "Teja Pristavec"
draft: false
type: "mypage"
---

# Teaching

### Methods

* _Statistical Methods in Sociology I_: graduate course, lab and statistics teaching assistant. Spring 2017.
* _Statistical Methods in Sociology II_: graduate course, lab and statistics teaching assistant. Fall 2016.
* _Introduction to Social Research_: undergraduate course, teaching assistant, two sections. Fall 2014.

> “Teja was an excellent TA , that made a difficult course relatively manageable. You could tell she cared about if we understood material, and she put a lot on effort into preparing for recitation. And she answered emails in a very timely manner, which was great.” (ISR, F14)


### Theory

* _Development of Sociological Theory_: undergraduate course, teaching assistant, two sections. Spring 2016.
* _Contemporary Sociological Theory_: undergraduate course, teaching assistant, two sections. Spring 2015, Fall 2015.

> “I liked how organized Teja was with presenting the materials. The instructional videos used were extremely helpful and it was great that she took the time to find them. The videos really helped clear up confusing concepts. Teja also did a really excellent job answering questions in a clear and concise manner. She made the material relevant to us and really cared about us understanding the material. She really tried to simply confusing concepts to help us understand.” (CST, S15)
>
> “Teja, overall, was very approachable and was always ready to do her best when it came to teaching, providing assistance, or responding via e-mail.” (CST, F15)
>
> “The instructor was always prepared and seemed to really value helping us learn the material. She was able to break it down into simple parts, making the recitation often more useful than the lecture. ” (CST, F15)


### Awards

* _Teaching Honor Roll_. Obtained average student rating above 4.5 or for teaching effectiveness and the overall quality of instruction. Spring 2016.


### Certificates

* _Teaching with Technology Certificate_: awarded by the Rutgers Teaching Assistant Project upon completing Basic Web Design, Basic RefWorks, Excel for Grading, and Managing a Course Website workshops.